server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN}

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${RAILWAY_PUBLIC_DOMAIN}/eureka/

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO