server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://go-bus-registry-service-production.up.railway.app/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    com.busapp: DEBUG
